### ISSUE TITLE
I am interested

### ISSUE THREAD

**Issue by richo67** [JosefRypacek/WeatherHub-WebAPI#1]
Hello, I would be interested to try your weatherhub webAPI. I just bought one and I am pretty annoyed that I can not see any graph and android app is really terrible.
Thanks for contacting me.

**Comment by JosefRypacek** [comment]
Hi,
if you want to see my code, please give me your bitbucket.org account, I'll share it with you.

Anyway, I found two interesting sites which could work too (and even better).

- they have new REST API http://www.mobile-alerts.eu 
- there is some service conradconnect.de with support of this devices
- there is also wh-observer.de (but I'm not sure if it's compatible)
