### ISSUE TITLE
I'm interested

### ISSUE THREAD

**Issue by silver-volt4** [JosefRypacek/WeatherHub-WebAPI#2]
Except you'll never reply.

Bummer.

**Comment by JosefRypacek** [comment]
Hi, please sent me an email to j.rypacek@gmail.com. I can give you access to my code, but I have a note here (see issue #1 )

http://www.mobile-alerts.eu - they have new REST API - there is some service conradconnect.de with support of this devices - there is also wh-observer.de (but I'm not sure if it's compatible)

I'm not using this app on my own, so maybe there is a better way (REST API or something similar) to get data from their servers.

**Comment by silver-volt4** [comment]
REST api sucks, it has support for like 5 devices. I'll email you right away.
